SELECT W.ID,P.AGE, W.COINS_NEEDED, W.POWER FROM WANDS AS W
INNER JOIN WANDS_PROPERTY AS P ON P.CODE = W.CODE
WHERE (P.AGE,W.POWER,W.COINS_NEEDED) IN (
SELECT P1.AGE,W1.POWER,MIN(W1.COINS_NEEDED) FROM WANDS AS W1 
JOIN WANDS_PROPERTY AS P1
ON W1.CODE=P1.CODE 
WHERE P1.IS_EVIL = 0
GROUP BY P1.AGE, W1.POWER)
ORDER BY W.POWER DESC,P.AGE DESC;