SELECT CONCAT(NAME,'(',SUBSTRING(OCCUPATION,1,1),')') FROM OCCUPATIONS
ORDER BY NAME ASC;

SELECT CONCAT ('There are a total of ',CAST(COUNT(*) AS CHAR)," ",LOWER(OCCUPATION),"s.") FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY COUNT(*) ASC;